### ISSUE TITLE
Support simple stereo panning

### ISSUE THREAD

**Issue by madwareru** [not-fl3/quad-snd#12]
Here is a link supposed to serve as a reference:
http://www.cs.cmu.edu/~music/icm-online/readings/panlaws/

It would be much easier to implement such a thing than some complex binaural sound model based on HRTF.
For simple 2D games this should do the work nicely

**Comment by mrDIMAS** [comment]
If you guys are interested, recently I released [hrtf](https://github.com/mrDIMAS/hrtf) crate which could help.

**Comment by not-fl3** [comment]
Out of `quad-snd` scope, feel free to fork and do something on top of quad-snd tho!
