### ISSUE TITLE
44.1khz audio plays faster & higher pitched when user device is at 48khz

### ISSUE THREAD

**Issue by Bombfuse** [not-fl3/quad-snd#20]

**Comment by PeteMrCoder** [comment]
Please see https://github.com/not-fl3/quad-snd/pull/22

**Comment by Bombfuse** [comment]
Tested the repo + branch and it seems to still have the same issues. I believe the only way to fix this is to resample the data if the data sample rate and device sample rate don't match.

**Comment by PeteMrCoder** [comment]
> 
> 
> Tested the repo + branch and it seems to still have the same issues. I believe the only way to fix this is to resample the data if the data sample rate and device sample rate don't match.

That is the route I originally went down, as mentioned in the comment https://github.com/not-fl3/quad-snd/pull/22#issue-597460871

Do you envision converting the samples on load or converting the stream in realtime? Would you combine all the samples before doing a conversion if done in realtime?

**Comment by not-fl3** [comment]
Should be fixed in 0.2 :)
