### ISSUE TITLE
'Native frameworks are only available on macOS targets' when targeting wasm32 on macOS

### ISSUE THREAD

**Issue by aaamarkin** [not-fl3/quad-snd#25]
Probably modify build.rs 
if cfg!(target_os = "macos") && cfg!(target_arch = "wasm32")

**Comment by not-fl3** [comment]
Oh, totally forgot about this - `cfg!(target_os)` will give you host OS data, not the cross-compilation target data!  

Thank you for the report, fixed with https://github.com/not-fl3/quad-snd/commit/48304b5a13144c3c3df3b3c3607e52e53c096cb0
