### ISSUE TITLE
"rust-lld: error: function signature mismatch: audio_init" wasm32-unknown-unknown error

### ISSUE THREAD

**Issue by eboatwright** [not-fl3/quad-snd#34]
I'm on MacOS Catalina 10.15.7, quad_snd version 0.1.0-alpha.1 (I'm using an old version because it's what @TanTanDev was using with his game using this, and the latest version doesn't work for me). Here's the full error:
note: rust-lld: error: function signature mismatch: audio_init
          >>> defined as (i32) -> i32 in /Users/{GAME_PATH}/target/wasm32-unknown-unknown/debug/deps/libquad_snd-9a787bf96d4e8e9b.rlib(quad_snd-9a787bf96d4e8e9b.quad_snd.f517ac66-cgu.14.rcgu.o)
          >>> defined as () -> void in /Users/{GAME_PATH}/target/wasm32-unknown-unknown/debug/deps/libquad_snd-b3ce2925c0a480b8.rlib(quad_snd-b3ce2925c0a480b8.quad_snd.371d2a4f-cgu.10.rcgu.o)

**Comment by not-fl3** [comment]
do you have a quad_snd-0.1 js files included as well?

**Comment by eboatwright** [comment]
No. Do I need that to do the "cargo build --target=wasm32-unknown-unknown" command?

**Comment by not-fl3** [comment]
Yes, `audio_init` is a javascript function, you need to find js files of the quad-snd version you are using and include them. If you want to check more of rust->js interop, check https://github.com/not-fl3/miniquad/wiki/JavaScript-interop

**Comment by eboatwright** [comment]
I'll check into that! :)

**Comment by eboatwright** [comment]
I copied the audio.js, build.sh, gl.js, and index.html and I'm still getting the same error

**Comment by not-fl3** [comment]
Double-check that you have this `audio_init` function in your js files. Note that 0.1 is a really, really old version and it may just not work well, I personally would not recommend using it unless you willing to sort out some very old bugs

**Comment by eboatwright** [comment]
Yeah it's there. I really don't know what to do, because I don't know why this error would happen when just building it, but I guess I'll try a newer version. Thanks for your help and time! :)

**Comment by eboatwright** [comment]
I updated to the latest version, and the wasm build works, but the local build has a bit of a delay :/
