### ISSUE TITLE
Support WAV sample rates different than 44100

### ISSUE THREAD

**Issue by madwareru** [not-fl3/quad-snd#4]
When I try to play a file with sample rate 22050 library panics with an assert.
It's not exactly what I've been expecting

**Comment by kakoeimon** [comment]
I just updated my project and I get this error : 
could not build output stream : The requested stream format is not supported by the device.

This PR is the problem : https://github.com/not-fl3/quad-snd/pull/11

I am on Window10 
 and this is what I was getting from quad-snd before this pr.
sound device : Speakers (Realtek(R) Audio) format Format { channels: 2, sample_rate: SampleRate(44100), data_type: F32 }

**Comment by madwareru** [comment]
Thanks for a feedback. I'll try to check it on windows and find a solution.

**Comment by madwareru** [comment]
> I just updated my project and I get this error :
> could not build output stream : The requested stream format is not supported by the device.
> 
> This PR is the problem : #11
> 
> I am on Window10
> and this is what I was getting from quad-snd before this pr.
> sound device : Speakers (Realtek(R) Audio) format Format { channels: 2, sample_rate: SampleRate(44100), data_type: F32 }

Could you provide a detailed call stack so it would be possible to find a cause of this problem sooner?

**Comment by kakoeimon** [comment]
I have no idea how to that.

**Comment by madwareru** [comment]
It should work as before when PR #13 would be merged.

**Comment by kakoeimon** [comment]
Yep. Just checked it.
