### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by bbstilson** [not-fl3/quad-snd#46]
Chatted about this in discord, but I think we need to do a version bump to get sounds to play on (some versions of?) linux in macroquad. If I change the quad-snd dependency from `version = "0.2"` to `git = "https://github.com/not-fl3/quad-snd"` then the examples in macroquad work.

The last release was 11 months ago, and I see there's been a few changes.

**Comment by not-fl3** [comment]
done :)

**Comment by bbstilson** [comment]
Thank you! Sounds are now playing on Linux in my game 🥳
