### ISSUE TITLE
panicked at 'Can't set rate'

### ISSUE THREAD

**Issue by sleepntsheep** [not-fl3/quad-snd#47]
I'm not using pipewire, just alsa & pulseaudio

    thread '<unnamed>' panicked at 'Can't set rate.', /home/sheep/.cargo/registry/s
    rc/github.com-1ecc6299db9ec823/quad-snd-0.2.5/src/alsa_snd.rs:57:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Audio thread died

with RUST_BACKTRACE=1

    thread '<unnamed>' panicked at 'Can't set rate.', /home/sheep/.cargo/registry/s
    rc/github.com-1ecc6299db9ec823/quad-snd-0.2.5/src/alsa_snd.rs:57:9
    stack backtrace:
       0: std::panicking::begin_panic
                 at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src
    /panicking.rs:616:12
       1: quad_snd::snd::setup_pcm_device
                 at /home/sheep/.cargo/registry/src/github.com-1ecc6299db9ec823/qua
    d-snd-0.2.5/src/alsa_snd.rs:57:9
       2: quad_snd::snd::audio_thread
                 at /home/sheep/.cargo/registry/src/github.com-1ecc6299db9ec823/qua
    d-snd-0.2.5/src/alsa_snd.rs:104:22
       3: quad_snd::snd::AudioContext::new::{{closure}}
                 at /home/sheep/.cargo/registry/src/github.com-1ecc6299db9ec823/qua
    d-snd-0.2.5/src/alsa_snd.rs:160:13

**Comment by Mirkopoj** [comment]
same as issue #45 

Install pipewire-alsa

**Comment by sleepntsheep** [comment]
whoops, ty
